In [2]:
import numpy as np

In [3]:
#create an array
a=[1,2,3,4]
arr = np.array(a)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [9]:
arr.shape

(4,)

In [10]:
# create an array 
a = [[1,2,3,4]]

arr = np.array(a)

In [11]:
arr.ndim

2

In [12]:
arr

array([[1, 2, 3, 4]])

In [13]:
arr.shape

(1, 4)

In [14]:
[[1,2,4],[4,6,5]]

[[1, 2, 4], [4, 6, 5]]

In [15]:
[[1,2,4],
 [4,6,5]]

[[1, 2, 4], [4, 6, 5]]

In [16]:
arr = np.array([[1,2,4],
 [4,6,5]])

In [17]:
arr.shape

(2, 3)

In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = np.arange(10,19)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [20]:
a = np.arange(10,200,12)
a

array([ 10,  22,  34,  46,  58,  70,  82,  94, 106, 118, 130, 142, 154,
       166, 178, 190])

In [1]:
a = np.linspace(1,10,41)
a

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a = np.linspace(1,10,41)
a

array([ 1.   ,  1.225,  1.45 ,  1.675,  1.9  ,  2.125,  2.35 ,  2.575,
        2.8  ,  3.025,  3.25 ,  3.475,  3.7  ,  3.925,  4.15 ,  4.375,
        4.6  ,  4.825,  5.05 ,  5.275,  5.5  ,  5.725,  5.95 ,  6.175,
        6.4  ,  6.625,  6.85 ,  7.075,  7.3  ,  7.525,  7.75 ,  7.975,
        8.2  ,  8.425,  8.65 ,  8.875,  9.1  ,  9.325,  9.55 ,  9.775,
       10.   ])

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
len(a)

10

In [6]:
a.shape

(10,)

In [7]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
a = np.arange(9).reshape(3,3)

In [10]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
b = np.arange(10,19).reshape(3,3)

In [12]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [13]:
b.dot(a)

array([[105, 138, 171],
       [132, 174, 216],
       [159, 210, 261]])

In [14]:
a*b

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [15]:
a+b

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [16]:
a-b

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])