In [1]:
import numpy as np

In [33]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#create a numpy array with values from 0 to 9
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#create 3*3 identity matrix using numpy
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#calculate the mean,mode,MEDIAN AND standard daviation of a given numpy array
a= np.random.randn(10)
a

array([ 0.34248512, -1.17731277, -1.72302531, -0.15025194,  1.25692082,
        1.13651418, -0.50356209, -0.6056188 ,  0.44146941, -0.94751758])

In [11]:
a.mean()

-0.19298989656484186

In [12]:
a.std()

0.9331050520359998

In [13]:
a=[1,2,3,4,5,6]

In [14]:
a

[1, 2, 3, 4, 5, 6]

In [15]:
median=3+4

In [16]:
median

7

In [17]:
7/2

3.5

In [18]:
#resshape 1D array with 2D array with two rows
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
#generate an array of 10 random integers between 1 and 100
d = np.random.randint(1,100,10)
d

array([11, 57, 61, 66, 86,  6, 35, 23, 86, 49])

In [21]:
#multiply two matrices :A[[1,2],[3,4]] and B[[5,6],[7,8]].
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [22]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [23]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [24]:
a*b

array([[ 5, 12],
       [21, 32]])

In [31]:
#exreact all even number feom an array
l=[1,2,3,4,5,6,7,8,9,10]
for i in l:
    if i%2==0:
        l.remove(i)
        print(l)

[1, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 8, 9, 10]
[1, 3, 5, 7, 9, 10]
[1, 3, 5, 7, 9]


In [32]:
#find the indices of the maximum and minimum calues in numpy array
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
a.min()

1

In [23]:
a.max()

4

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
#b=(0+1+2+3+4)
#b

10

In [40]:
#c=b/5

In [41]:
#c

2.0

In [43]:
#normalize a given array (substract the mean and divide by the standard daviation).
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
a.mean()

2.0

In [26]:
a.std()

1.4142135623730951

In [27]:
b=a.mean()/a.std()

In [28]:
b

1.414213562373095

In [29]:
#concatenate two arrays horizontally and vertically
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b=np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])