In [1]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(5)
s = pd.Series (a, index = list('abcde'))
s


a    0
b    1
c    2
d    3
e    4
dtype: int32

In [8]:
arr = np.random.randint(15,size = (8,3))
df = pd.DataFrame(arr,columns = list('ABC'))


In [9]:
df


A   B   C
0   5   3   6
1   0  13  12
2  14   0   7
3   3   3   3
4   7   5  13
5   8  13   0
6  12   9   4
7   2   2  10

In [4]:
s

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [5]:
index = pd.date_range('23/08/2023',periods = 6)
index

C:\Users\ARUN\AppData\Local\Temp\ipykernel_5396\1241399040.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  index = pd.date_range('23/08/2023',periods = 6)


DatetimeIndex(['2023-08-23', '2023-08-24', '2023-08-25', '2023-08-26',
               '2023-08-27', '2023-08-28'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df.head(3)  #find top values

A   B   C
0   5   3   6
1   0  13  12
2  14   0   7

In [12]:
df.tail(3)  #find bottom values

A   B   C
5  8   1   8
6  9   0  10
7  2  12   8

In [11]:
df['S'] = s  #find series

In [12]:
s1 = pd.Series(np.arange(5)) 


In [13]:
df['S1'] = s1

In [14]:
df

A   B   C   S   S1
0   5   3   6 NaN  0.0
1   0  13  12 NaN  1.0
2  14   0   7 NaN  2.0
3   3   3   3 NaN  3.0
4   7   5  13 NaN  4.0
5   8  13   0 NaN  NaN
6  12   9   4 NaN  NaN
7   2   2  10 NaN  NaN

In [15]:
df.info()  #information of table,types of column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       8 non-null      int32  
 1   B       8 non-null      int32  
 2   C       8 non-null      int32  
 3   S       0 non-null      float64
 4   S1      5 non-null      float64
dtypes: float64(2), int32(3)
memory usage: 356.0 bytes


In [16]:
df.describe()  #describe table,(find mean,madian)

A          B          C    S        S1
count   8.000000   8.000000   8.000000  0.0  5.000000
mean    6.375000   6.000000   6.875000  NaN  2.000000
std     4.867898   5.042675   4.549333  NaN  1.581139
min     0.000000   0.000000   0.000000  NaN  0.000000
25%     2.750000   2.750000   3.750000  NaN  1.000000
50%     6.000000   4.000000   6.500000  NaN  2.000000
75%     9.000000  10.000000  10.500000  NaN  3.000000
max    14.000000  13.000000  13.000000  NaN  4.000000

In [17]:
df.isna().sum()   #find null values(means of 3 ,3 rows are empty)

A     0
B     0
C     0
S     8
S1    3
dtype: int64

In [20]:
df.drop(['S'],axis=1,inplace=True)   #for column=axis1,row = axis 0 , replace is use for permanent changes
df

A   B   C
0   5   3   6
1   0  13  12
2  14   0   7
3   3   3   3
4   7   5  13
5   8  13   0
6  12   9   4
7   2   2  10

In [21]:
df.dropna()

A   B   C
0   5   3   6
1   0  13  12
2  14   0   7
3   3   3   3
4   7   5  13
5   8  13   0
6  12   9   4
7   2   2  10

In [22]:
df

A   B   C
0   5   3   6
1   0  13  12
2  14   0   7
3   3   3   3
4   7   5  13
5   8  13   0
6  12   9   4
7   2   2  10

In [23]:
df.to_numpy()    #to_numpy use to convert df into array

array([[ 5,  3,  6],
       [ 0, 13, 12],
       [14,  0,  7],
       [ 3,  3,  3],
       [ 7,  5, 13],
       [ 8, 13,  0],
       [12,  9,  4],
       [ 2,  2, 10]])

In [24]:
df[df<12]    #

A    B     C
0  5.0  3.0   6.0
1  0.0  NaN   NaN
2  NaN  0.0   7.0
3  3.0  3.0   3.0
4  7.0  5.0   NaN
5  8.0  NaN   0.0
6  NaN  9.0   4.0
7  2.0  2.0  10.0

In [25]:
df[df<12]['A']

0    5.0
1    0.0
2    NaN
3    3.0
4    7.0
5    8.0
6    NaN
7    2.0
Name: A, dtype: float64

In [26]:
df

A   B   C
0   5   3   6
1   0  13  12
2  14   0   7
3   3   3   3
4   7   5  13
5   8  13   0
6  12   9   4
7   2   2  10

In [27]:
d = np.arange(27).reshape(3,3,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
d[::2,:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])

SyntaxError: invalid syntax (3313443315.py, line 1)