In [1]:
import numpy as np

In [1]:
import numpy as np

In [1]:
import numpy as np


In [2]:
a = np.linspace(1,20,10)
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [3]:
a = np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
a = np.ones((4,7))
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [5]:
a = [2,4,23,5,7,2,1,3,45,0]

In [6]:
arr = np.array(a)

In [7]:
arr

array([ 2,  4, 23,  5,  7,  2,  1,  3, 45,  0])

In [8]:
len(arr)

10

In [9]:
arr.reshape((10,1))

array([[ 2],
       [ 4],
       [23],
       [ 5],
       [ 7],
       [ 2],
       [ 1],
       [ 3],
       [45],
       [ 0]])

In [10]:
arr = np.arrange(25).reshape((5,5))

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
arr

array([ 2,  4, 23,  5,  7,  2,  1,  3, 45,  0])

In [12]:
arr = np.arange(25).reshape((5,5))

In [13]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
#indexing
arr[0]

array([0, 1, 2, 3, 4])

In [15]:
arr[3]

array([15, 16, 17, 18, 19])

In [16]:
#arr[r0w.column]
arr[3:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
arr[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a[-1]

0

In [19]:
arr[-1]

array([20, 21, 22, 23, 24])

In [20]:
arr[-2]

array([15, 16, 17, 18, 19])

In [21]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr[0,0]

0

In [23]:
arr[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [24]:
a=[[1,2,3],[3,4,5]]

In [25]:
a[1][1]

4

In [26]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
arr[:2,1:3]

array([[1, 2],
       [6, 7]])

In [29]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
a[::2]

[[1, 2, 3]]

In [31]:
arr[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [32]:
arr = np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [1]:
import numpy as np

In [2]:
a = np.linspace(1,20,11)
a

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1, 20. ])

In [3]:
a = np.linspace(1,10,2)
a

array([ 1., 10.])

In [4]:
a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [7]:
a = np.linspace(0,10,15)
a

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [8]:
arr[arr%2==0]

NameError: name 'arr' is not defined

In [9]:
arr


NameError: name 'arr' is not defined

In [10]:
arr = np.arange(10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [13]:
arr[(arr<5)&(arr%2==0)]

array([0, 2, 4])

In [14]:
arr[(arr<5)] ^(arr%2 == 0)

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

In [15]:
arr[(arr<5)] ^(arr%2 == 0)

ValueError: operands could not be broadcast together with shapes (5,) (10,) 