In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.layers import Embedding, SimpleRNN , Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
data =[

    ("I absolutely loved this movie!", "positive"),

    ("The acting was terrible and the plot was boring", "negative"),

    ("This film was masterpeace.", "positive"),

    ("I couldn't stand watching it, a complete waste of time", "negative"),

    ("The cinematography was stunning, a must-watch!", "positive")

]

In [4]:
reviews, sentiments = zip(*data)

In [5]:
reviews

('I absolutely loved this movie!',
 'The acting was terrible and the plot was boring',
 'This film was masterpeace.',
 "I couldn't stand watching it, a complete waste of time",
 'The cinematography was stunning, a must-watch!')

In [6]:
sentiments

('positive', 'negative', 'positive', 'negative', 'positive')

In [7]:
tokens = Tokenizer()
tokens.fit_on_texts(reviews)

In [8]:
vocab_size = len(tokens.word_index)+1
vocab_size

28

In [9]:
seq = tokens.texts_to_sequences(reviews)

In [10]:
seq

[[3, 6, 7, 4, 8],
 [2, 9, 1, 10, 11, 2, 12, 1, 13],
 [4, 14, 1, 15],
 [3, 16, 17, 18, 19, 5, 20, 21, 22, 23],
 [2, 24, 1, 25, 5, 26, 27]]

In [11]:
max_length = max([len(i) for i in seq])
max_length

10

In [12]:
pad_seq = sequence.pad_sequences(seq, maxlen=max_length, padding="post")

In [13]:
pad_seq

array([[ 3,  6,  7,  4,  8,  0,  0,  0,  0,  0],
       [ 2,  9,  1, 10, 11,  2, 12,  1, 13,  0],
       [ 4, 14,  1, 15,  0,  0,  0,  0,  0,  0],
       [ 3, 16, 17, 18, 19,  5, 20, 21, 22, 23],
       [ 2, 24,  1, 25,  5, 26, 27,  0,  0,  0]])

In [14]:
labels = np.array([1 if i=="positive" else 0 for i in sentiments])
labels

array([1, 0, 1, 0, 1])

In [15]:
model = Sequential([
    Embedding(vocab_size, 20, input_length=max_length),
    SimpleRNN(20),
    Dense(1, activation="sigmoid")
])

In [16]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [17]:
model.fit(pad_seq, labels, epochs=15, verbose=1)

Epoch 1/15


1/1 [==============================] - 4s 4s/step - loss: 0.7159 - accuracy: 0.4000
Epoch 2/15
1/1 [==============================] - 0s 19ms/step - loss: 0.6949 - accuracy: 0.4000
Epoch 3/15
1/1 [==============================] - 0s 15ms/step - loss: 0.6748 - accuracy: 0.6000
Epoch 4/15
1/1 [==============================] - 0s 21ms/step - loss: 0.6554 - accuracy: 0.8000
Epoch 5/15
1/1 [==============================] - 0s 16ms/step - loss: 0.6367 - accuracy: 1.0000
Epoch 6/15
1/1 [==============================] - 0s 16ms/step - loss: 0.6183 - accuracy: 1.0000
Epoch 7/15
1/1 [==============================] - 0s 21ms/step - loss: 0.6004 - accuracy: 1.0000
Epoch 8/15
1/1 [==============================] - 0s 18ms/step - loss: 0.5828 - accuracy: 1.0000
Epoch 9/15
1/1 [==============================] - 0s 17ms/step - loss: 0.5653 - accuracy: 1.0000
Epoch 10/15
1/1 [==============================] - 0s 17ms/step - loss: 0.5480 - accuracy: 1.0000
Epoch 11/15
1/1 [============

In [18]:
new_sent = "I was blown away by the incredible performance and gripping storyline"

In [19]:
new_seq = tokens.texts_to_sequences([new_sent])

In [20]:
new_pad_seq = sequence.pad_sequences(new_seq, maxlen=max_length, padding="post")

In [21]:
new_pad_seq

array([[ 3,  1,  2, 11,  0,  0,  0,  0,  0,  0]])

In [22]:
pred = model.predict(new_pad_seq)

1/1 [==============================] - 1s 501ms/step


In [23]:
sentiment = "Positive" if pred >= 0.5 else "negative" 

In [24]:
sentiment

'Positive'